name: Build LaTeX document
on:
  push:
    branches: 
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: pdflatex
          args: ""
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          path: main.pdf