name: Build LaTeX document
on:
  push:
    branches: 
      - master
      - develop
jobs:
  build_latex:
    runs-on: ubuntu-latest
    name: Build PDF
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          compiler: latexmk
          args: -pdf -file-line-error -interaction=nonstopmode
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Proyecto_Integrador
          path: main.pdf